# - name: SpacyNLP
#   model: "pt_core_news_sm" # or any language model
#   case_sensitive: false
# - name: SpacyTokenizer
# - name: LexicalSyntacticFeaturizer
# - name: SpacyFeaturizer
# - name: CountVectorsFeaturizer
# - name: CountVectorsFeaturizer
#   analyzer: char_wb
#   min_ngram: 1
#   max_ngram: 4
# - name: DIETClassifier
#   epochs: 200
# - name: rasa_addons.nlu.components.gazette.Gazette
# - name: rasa_addons.nlu.components.intent_ranking_canonical_example_injector.IntentRankingCanonicalExampleInjector
# - name: EntitySynonymMapper

# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: pt

pipeline:
  # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
  # If you'd like to customize it, uncomment and adjust the pipeline.
  # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: WhitespaceTokenizer
    token_pattern: (?u)\b\w+\b
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
# policies:
#   # # No configuration for policies was provided. The following default policies were used to train your model.
#   # # If you'd like to customize them, uncomment and adjust the policies.
#   # # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
policies:
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
  - max_history: 6
    name: AugmentedMemoizationPolicy
  - name: TEDPolicy
    max_history: 10
    epochs: 20
    batch_size:
      - 32
      - 64
