# NB! when updating make sure the version is in sync with:
# * rasa version in requirements.txt
# * RASA_VERSION and RASA_X_VERSION  in .github/workflows/continuous-deployment.yml
# Pull SDK image as base image
FROM rasa/rasa-sdk:3.2.0

# Use subdirectory as working directory
WORKDIR /app

# Copy actions requirements
COPY requirements-actions.txt ./

# Change to root user to install dependencies
USER root

RUN apt-get update -qq && \
  apt-get install -y --no-install-recommends \
  python3 \
  python3-venv \
  python3-pip \
  python3-dev \
  # required by psycopg2 at build and runtime
  libpq-dev \
  libxmlsec1-dev \
  # required for health check
  curl \
  && apt-get autoremove -y

# Make sure that all security updates are installed
RUN apt-get update && apt-get dist-upgrade -y --no-install-recommends

# Install extra requirements for actions code
RUN pip install --upgrade pip && pip install -r requirements-actions.txt

# Copy actions code to working directory
COPY . /app/actions
# COPY ./../config /app/config

# Install modules from setup.py

# COPY readme.md /app
# RUN pip install . --no-cache-dir

# Download spacy language data
# RUN python -m spacy download pt_core_news_lg

# Don't use root user to run code
USER 1001

# Start the action server
CMD ["start", "--actions", "actions.actions"]
